appserver:
  image: gunicorn
  links:
    - db
  ports:
    - "5000:5000"
  volumes:
    - .:/opt/app
    - logs:/sharedlogs
nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - nginx.conf.d:/etc/nginx/conf.d
    - logs:/var/log/nginx/
  links:
    - appserver
db:
  image: postgres
  environment:
    - POSTGRES_DB=foodcalc
    - POSTGRES_USER=foodcalc
    - POSTGRES_PASSWORD=foodcalc
